schema {
  query: Queries
  mutation: Mutations
  subscription: Subscriptions
}
scalar Json
scalar Long
scalar Unit

union DMScreenEvent = Add | CombatLog | Copy | GeneralLog | Move | Remove | Replace | Test

enum Alignment {
  chaoticEvil
  chaoticGood
  chaoticNeutral
  lawfulEvil
  lawfulGood
  lawfulNeutral
  neutralEvil
  neutralGood
  trueNeutral
  unaligned
}

enum Biome {
  Arctic
  Coastal
  Desert
  Forest
  Grassland
  Hill
  Mountain
  Swamp
  Underdark
  Underwater
  Urban
}

enum CreatureSize {
  gargantuan
  huge
  large
  medium
  small
  tiny
}

enum DND5eEntityType {
  campaign
  encounter
  monster
  nonPlayerCharacter
  playerCharacter
  scene
  spell
}

enum GameSystem {
  dnd5e
  pathfinder2e
  starTrekAdventures
}

enum MonsterSearchOrder {
  alignment
  biome
  challengeRating
  monsterType
  name
  random
  size
}

enum MonsterType {
  Aberration
  Beast
  Celestial
  Construct
  Dragon
  Elemental
  Fey
  Fiend
  Giant
  Humanoid
  Monstrosity
  Ooze
  Plant
  Undead
}

enum OrderDirection {
  asc
  desc
}

input CampaignHeaderInput {
  id: Long!
  dmUserId: Long!
  name: String!
  gameSystem: GameSystem!
}

input EncounterHeaderInput {
  id: Long!
  campaignId: Long!
  name: String!
  status: String!
  sceneId: Long
  orderCol: Int!
}

input MonsterHeaderInput {
  id: Long!
  name: String!
  monsterType: MonsterType!
  biome: Biome
  alignment: Alignment
  cr: Float!
  xp: Long!
  armorClass: Int!
  maximumHitPoints: Int!
  size: CreatureSize!
  initiativeBonus: Int!
}

input NonPlayerCharacterHeaderInput {
  id: Long!
  campaignId: Long!
  name: String!
}

input PlayerCharacterHeaderInput {
  id: Long!
  campaignId: Long!
  name: String!
  playerName: String
}

input SceneHeaderInput {
  id: Long!
  campaignId: Long!
  name: String!
  orderCol: Int!
  isActive: Boolean!
}

input SourceInput {
  name: String!
  id: String!
  url: String
}

type Add {
  path: JsonPath!
  value: Json!
}

type Background {
  name: String!
}

type CampaignHeader {
  id: Long!
  dmUserId: Long!
  name: String!
  gameSystem: GameSystem!
}

type CharacterClass {
  id: String!
  hitDice: String!
}

type CombatLog {
  message: String!
  json: Json!
}

type Copy {
  from: JsonPath!
  to: JsonPath!
}

type DND5eCampaign {
  header: CampaignHeader!
  jsonInfo: Json!
  version: String!
}

type Encounter {
  header: EncounterHeader!
  jsonInfo: Json!
  version: String!
}

type EncounterHeader {
  id: Long!
  campaignId: Long!
  name: String!
  status: String!
  sceneId: Long
  orderCol: Int!
}

type GeneralLog {
  message: String!
  json: Json!
}

type JsonPath {
  value: String!
}

type Monster {
  header: MonsterHeader!
  jsonInfo: Json!
  version: String!
}

type MonsterHeader {
  id: Long!
  name: String!
  monsterType: MonsterType!
  biome: Biome
  alignment: Alignment
  cr: Float!
  xp: Long!
  armorClass: Int!
  maximumHitPoints: Int!
  size: CreatureSize!
  initiativeBonus: Int!
}

type MonsterSearchResults {
  results: [Monster!]!
  total: Long!
}

type Move {
  from: JsonPath!
  to: JsonPath!
}

type Mutations {
  upsertCampaign(header: CampaignHeaderInput!, jsonInfo: Json!, version: String!): Long
  upsertScene(header: SceneHeaderInput!, jsonInfo: Json!, version: String!): Long
  upsertPlayerCharacter(header: PlayerCharacterHeaderInput!, jsonInfo: Json!, version: String!): Long
  upsertNonPlayerCharacter(header: NonPlayerCharacterHeaderInput!, jsonInfo: Json!, version: String!): Long
  upsertMonster(header: MonsterHeaderInput!, jsonInfo: Json!, version: String!): Long
  upsertEncounter(header: EncounterHeaderInput!, jsonInfo: Json!, version: String!): Long
  applyOperations(entityType: DND5eEntityType!, id: Long!, events: [Json!]!): Unit
}

type NonPlayerCharacter {
  header: NonPlayerCharacterHeader!
  jsonInfo: Json!
  version: String!
}

type NonPlayerCharacterHeader {
  id: Long!
  campaignId: Long!
  name: String!
}

type PlayerCharacter {
  header: PlayerCharacterHeader!
  jsonInfo: Json!
  version: String!
}

type PlayerCharacterHeader {
  id: Long!
  campaignId: Long!
  name: String!
  playerName: String
}

type Queries {
  campaigns: [CampaignHeader!]
  campaign(value: Long!): DND5eCampaign
  playerCharacters(value: Long!): [PlayerCharacter!]
  scenes(value: Long!): [Scene!]
  nonPlayerCharacters(value: Long!): [NonPlayerCharacter!]
  encounters(value: Long!): [Encounter!]
  bestiary(name: String, challengeRating: Float, size: CreatureSize, alignment: Alignment, biome: Biome, monsterType: MonsterType, source: SourceInput, orderCol: MonsterSearchOrder!, orderDir: OrderDirection!, page: Int!, pageSize: Int!): MonsterSearchResults
  sources: [Source!]
  classes: [CharacterClass!]
  races: [Race!]
  backgrounds: [Background!]
  subclasses(value: String!): [SubClass!]
}

type Race {
  name: String!
}

type Remove {
  path: JsonPath!
}

type Replace {
  path: JsonPath!
  value: Json!
}

type Scene {
  header: SceneHeader!
  jsonInfo: Json!
  version: String!
}

type SceneHeader {
  id: Long!
  campaignId: Long!
  name: String!
  orderCol: Int!
  isActive: Boolean!
}

type Source {
  name: String!
  id: String!
  url: String
}

type SubClass {
  name: String!
}

type Subscriptions {
  campaignStream(entityType: DND5eEntityType!, id: Long!, events: [Json!]!): DMScreenEvent
}

type Test {
  path: JsonPath!
  value: Json!
}
