drop table if exists DND5eRandomTableEntry;
drop table if exists DND5eRandomTable;

create table DND5eRandomTable
(
    `id`        int(11) NOT NULL AUTO_INCREMENT,
    `name`      text    NOT NULL,
    `tableType` text    NOT NULL,
    `subType`   text    NOT NULL,
    `diceRoll`  text    NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

create table DND5eRandomTableEntry
(
    `tableId`     int(11) NOT NULL,
    `rangeLow`    int(11) NOT NULL,
    `rangeHigh`   int(11) NOT NULL,
    `name`        text    NOT NULL,
    `description` text    NOT NULL,
    PRIMARY KEY (`tableId`, `rangeLow`, `rangeHigh`),
    FOREIGN KEY (`tableId`) REFERENCES DND5eRandomTable (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

insert into DND5eRandomTable (id, name, tableType, subType, diceRoll)
values (1, '10 GP Gemstones', 'treasure', 'Arcana-Common', '1d12'),
       (2, '50 GP Gemstones', 'treasure', 'Arcana-Common', '1d12'),
       (3, '100 GP Gemstones', 'treasure', 'Arcana-Uncommon', '1d10'),
       (4, '500 GP Gemstones', 'treasure', 'Arcana-Uncommon', '1d6'),
       (5, '1000 GP Gemstones', 'treasure', 'Arcana-Rare', '1d8'),
       (6, '5000 GP Gemstones', 'treasure', 'Arcana-Rare', '1d4'),
       (7, 'Arcana Common', 'treasure', 'Arcana-Common', '1d100'),
       (8, 'Arcana Uncommon', 'treasure', 'Arcana-Uncommon', '1d100'),
       (9, 'Arcana Rare', 'treasure', 'Arcana-Rare', '1d100'),
       (10, 'Arcana Very Rare', 'treasure', 'Arcana-Very Rare', '1d100'),
       (11, 'Arcana Legendary', 'treasure', 'Arcana-Legendary', '1d100'),
       (12, 'Armaments Common', 'treasure', 'Armaments-Common', '1d100'),
       (13, 'Armaments Uncommon', 'treasure', 'Armaments-Uncommon', '1d100'),
       (14, 'Armaments Rare', 'treasure', 'Armaments-Rare', '1d100'),
       (15, 'Armaments Very Rare', 'treasure', 'Armaments-Very Rare', '1d100'),
       (16, 'Armaments Legendary', 'treasure', 'Armaments-Legendary', '1d100'),
       (17, 'Implements Common', 'treasure', 'Implements-Common', '1d100'),
       (18, 'Implements Uncommon', 'treasure', 'Implements-Uncommon', '1d100'),
       (19, 'Implements Rare', 'treasure', 'Implements-Rare', '1d100'),
       (20, 'Implements Very Rare', 'treasure', 'Implements-Very Rare', '1d100'),
       (21, 'Implements Legendary', 'treasure', 'Implements-Legendary', '1d100'),
       (22, 'Relics Common', 'treasure', 'Relics-Common', '1d100'),
       (23, 'Relics Uncommon', 'treasure', 'Relics-Uncommon', '1d100'),
       (24, 'Relics Rare', 'treasure', 'Relics-Rare', '1d100'),
       (25, 'Relics Very Rare', 'treasure', 'Relics-Very Rare', '1d100'),
       (26, 'Relics Legendary', 'treasure', 'Relics-Legendary', '1d100'),
       (27, '25 GP Art Objects', 'treasure', 'Relics-Common', '1d10'),
       (28, '250 GP Art Objects', 'treasure', 'Relics-Uncommon', '1d10'),
       (29, '750 GP Art Objects', 'treasure', 'Relics-Rare', '1d10'),
       (30, '2500 GP Art Objects', 'treasure', 'Relics-Very Rare', '1d10'),
       (31, '7500 GP Art Objects', 'treasure', 'Relics-Legendary', '1d10'),
       (32, 'Trinkets', 'treasure', '', '1d100'),

       (33, 'Common Name', 'npc', '', 'xx'),
       (34, 'Common Last Name', 'npc', '', 'xx'),
       (35, 'Guttural Name', 'npc', '', 'xx'),
       (36, 'Guttural Last Name', 'npc', '', 'xx'),
       (37, 'Lyrical Name', 'npc', '', 'xx'),
       (38, 'Lyrical Last Name', 'npc', '', 'xx'),
       (39, 'Mono Syllabic Name', 'npc', '', 'xx'),
       (40, 'Mono Syllabic Last Name', 'npc', '', 'xx'),
       (41, 'Synister Name', 'npc', '', 'xx'),
       (42, 'Synister Last Name', 'npc', '', 'xx'),
       (43, 'Whimsical Name', 'npc', '', 'xx'),
       (44, 'Whimsical Last Name', 'npc', '', 'xx'),

       (45, 'Appearance', 'npc', '', 'xx'),
       (46, 'Secret', 'npc', '', 'xx'),

       (47, 'Settlement Defining Trait', 'environment', '', 'xx'),
       (48, 'Settlement Claim to Fame', 'environment', '', 'xx'),
       (49, 'Settlement Current Calamities', 'environment', '', 'xx'),
       (50, 'Settlement Local Leaders', 'environment', '', 'xx'),
       (51, 'Tavern Names First Part', 'environment', '', 'xx'),
       (52, 'Tavern Names Second Part', 'environment', '', 'xx'),
       (53, 'Random Shop', 'environment', '', 'xx'),
       (54, 'Dungeon Quirks', 'environment', '', 'xx'),
       (55, 'Dungeon Decay', 'environment', '', 'xx'),

       (56, 'Level 1-4 Adventure Situations', 'adventure', '', 'xx'),
       (57, 'Level 5-10 Adventure Situations', 'adventure', '', 'xx'),
       (58, 'Level 11-16 Adventure Situations', 'adventure', '', 'xx'),
       (59, 'Level 17-20 Adventure Situations', 'adventure', '', 'xx'),
       (60, 'Patron Hoooks', 'adventure', '', 'xx'),
       (61, 'Supernatural Hooks', 'adventure', '', 'xx'),
       (62, 'Happenstance Hooks', 'adventure', '', 'xx'),
       (63, 'Adventure Climax', 'adventure', '', 'xx'),
       (64, 'Adventure Connections', 'adventure', '', 'xx'),

       (65, 'Initial Monster Attitude', 'encounter', '', 'xx'),
       (66, 'Monster Personality', 'encounter', '', 'xx'),
       (67, 'Monster Relationships', 'encounter', '', 'xx'),
       (68, 'Urban Chase Complications', 'encounter', '', 'xx'),
       (69, 'Wilderness Chase Complications', 'encounter', '', 'xx')
;

insert into DND5eRandomTableEntry (tableId, rangeLow, rangeHigh, name, description)
values
-- Treasure: Gems
(1, 1, 1, 'Azurite (mottled deep blue)', ''),
(1, 2, 2, 'Banded agate (striped brown, blue, white, or red)', ''),
(1, 3, 3, 'Blue quartz (pale blue)', ''),
(1, 4, 4, 'Eye agate (circles of gray, white, brown, blue, or green)', ''),
(1, 5, 5, 'Hematite (gray black)', ''),
(1, 6, 6, 'Lapis lazuli (light and dark blue with yellow flecks)', ''),
(1, 7, 7, 'Malachite (striated light and dark green)', ''),
(1, 8, 8, 'Moss agate (pink or yellow white with mossy gray or green markings)', ''),
(1, 9, 9, 'Obsidian (black)', ''),
(1, 10, 10, 'Rhodochrosite (light pink)', ''),
(1, 11, 11, 'Tiger eye (brown with golden center)', ''),
(1, 12, 12, 'Turquoise (light blue green)', ''),
(2, 1, 1, 'Bloodstone (dark gray with red flecks)', ''),
(2, 2, 2, 'Carnelian (orange to red brown)', ''),
(2, 3, 3, 'Chalcedony (white)', ''),
(2, 4, 4, 'Chrysoprase (green)', ''),
(2, 5, 5, 'Citrine (pale yellow brown)', ''),
(2, 6, 6, 'Jasper (blue, black, or brown)', ''),
(2, 7, 7, 'Moonstone (white with pale-blue glow)', ''),
(2, 8, 8, 'Onyx (bands of black and white, or pure black or white)', ''),
(2, 9, 9, 'Quartz (white, smoky gray, or yellow)', ''),
(2, 10, 10, 'Sardonyx (bands of red and white)', ''),
(2, 11, 11, 'Star rose quartz (rosy stone with white star-shaped center)', ''),
(2, 12, 12, 'Zircon (pale blue green)', ''),
(3, 1, 1, 'Amber (watery gold to rich gold)', ''),
(3, 2, 2, 'Amethyst (deep purple)', ''),
(3, 3, 3, 'Chrysoberyl (yellow green to pale green)', ''),
(3, 4, 4, 'Coral (crimson)', ''),
(3, 5, 5, 'Garnet (red, brown green, or violet)', ''),
(3, 6, 6, 'Jade (light green, deep green, or white)', ''),
(3, 7, 7, 'Jet (deep black)', ''),
(3, 8, 8, 'Pearl (lustrous white, yellow, or pink)', ''),
(3, 9, 9, 'Spinel (red, red brown, or deep green)', ''),
(3, 10, 10, 'Tourmaline (pale green, blue, brown, or red)', ''),
(4, 1, 1, 'Alexandrite (dark green)', ''),
(4, 2, 2, 'Aquamarine (pale blue green)', ''),
(4, 3, 3, 'Black pearl (pure black)', ''),
(4, 4, 4, 'Blue spinel (deep blue)', ''),
(4, 5, 5, 'Peridot (rich olive green)', ''),
(4, 6, 6, 'Topaz (golden yellow)', ''),
(5, 1, 1, 'Black opal (dark green with black mottling and golden flecks)', ''),
(5, 2, 2, 'Blue sapphire (medium blue)', ''),
(5, 3, 3, 'Emerald (deep bright green)', ''),
(5, 4, 4, 'Fire opal (fiery red)', ''),
(5, 5, 5, 'Opal (pale blue with green and golden mottling)', ''),
(5, 6, 6, 'Star ruby (ruby with white star-shaped center)', ''),
(5, 7, 7, 'Star sapphire (blue sapphire with white star-shaped center)', ''),
(5, 8, 8, 'Yellow sapphire (fiery yellow or yellow green)', ''),
(6, 1, 1, 'Black sapphire (lustrous black with glowing highlights)', ''),
(6, 2, 2, 'Diamond (blue white, canary, pink, brown, or blue)', ''),
(6, 3, 3, 'Jacinth (fiery orange)', ''),
(6, 4, 4, 'Ruby (clear red to deep crimson)', ''),
-- Treasure: Magic items
(7, 01, 02, 'Bead of Nourishment', ''),
(7, 03, 04, 'Bead of Refreshment', ''),
(7, 05, 07, 'Candle of the Deep', ''),
(7, 08, 10, 'Cloak of Billowing', ''),
(7, 11, 13, 'Cloak of Many Fashions', ''),
(7, 14, 15, 'Clothes of Mending', ''),
(7, 16, 17, 'Dark Shard Amulet', ''),
(7, 18, 19, 'Enduring Spellbook', ''),
(7, 20, 21, 'Ersatz Eye', ''),
(7, 22, 24, 'Hat of Vermin', ''),
(7, 25, 27, 'Hat of Wizardry', ''),
(7, 28, 29, 'Heward’s Handy Spice Pouch', ''),
(7, 30, 31, 'Horn of Silent Alarm', ''),
(7, 32, 33, 'Instrument of Illusions', ''),
(7, 34, 35, 'Instrument of Scribing', ''),
(7, 36, 37, 'Lock of Trickery', ''),
(7, 38, 40, 'Mystery Key', ''),
(7, 41, 42, 'Orb of Direction', ''),
(7, 43, 44, 'Orb of Time', ''),
(7, 45, 46, 'Perfume of Bewitching', ''),
(7, 47, 49, 'Pipe of Smoke Monsters', ''),
(7, 50, 52, 'Potion of Climbing', ''),
(7, 53, 55, 'Potion of Comprehension', ''),
(7, 56, 58, 'Pot of Awakening', ''),
(7, 59, 60, 'Prosthetic Limb', ''),
(7, 61, 64, 'Rival Coin', ''),
(7, 65, 66, 'Rope of Mending', ''),
(7, 67, 68, 'Ruby of the War Mage', ''),
(7, 69, 82, 'Spell Scroll (cantrip or level 1 spell)', ''),
(7, 83, 84, 'Staff of Adornment', ''),
(7, 85, 86, 'Staff of Birdcalls', ''),
(7, 87, 89, 'Staff of Flowers', ''),
(7, 90, 92, 'Talking Doll', ''),
(7, 93, 94, 'Tankard of Sobriety', ''),
(7, 95, 97, 'Wand of Conducting', ''),
(7, 98, 00, 'Wand of Pyrotechnics', ''),
-- Treasure: Art objects
(27, 1, 1, 'Silver ewer', ''),
(27, 2, 2, 'Carved bone statuette', ''),
(27, 3, 3, 'Gold bracelet', ''),
(27, 4, 4, 'Cloth-of-gold vestments', ''),
(27, 5, 5, 'Black velvet mask stitched with silver thread', ''),
(27, 6, 6, 'Copper chalice with silver filigree', ''),
(27, 7, 7, 'Pair of engraved bone dice', ''),
(27, 8, 8, 'Handheld mirror set in a painted wooden frame', ''),
(27, 9, 9, 'Embroidered silk handkerchief', ''),
(27, 10, 10, 'Gold locket with a painted portrait inside', ''),
(28, 1, 1, 'Gold ring set with bloodstones', ''),
(28, 2, 2, 'Carved ivory statuette', ''),
(28, 3, 3, 'Bejeweled gold bracelet', ''),
(28, 4, 4, 'Silver necklace with a gemstone pendant', ''),
(28, 5, 5, 'Bronze crown', ''),
(28, 6, 6, 'Silk vestments with gold embroidery', ''),
(28, 7, 7, 'Well-made tapestry that is 10 feet by 10 feet', ''),
(28, 8, 8, 'Brass mug with jade inlay', ''),
(28, 9, 9, 'Box of turquoise animal figurines', ''),
(28, 10, 10, 'Gold birdcage with electrum filigree', ''),
(29, 1, 1, 'Silver chalice set with moonstones', ''),
(29, 2, 2, 'Bundle of sheet music representing the lost dirges of a famous composer', ''),
(29, 3, 3, 'Carved wooden harp with ivory inlay and zircon gems', ''),
(29, 4, 4, 'Gold idol', ''),
(29, 5, 5, 'Gold comb shaped like a dragon with red garnets as eyes', ''),
(29, 6, 6, 'Bottle stopper cork embossed with gold leaf and set with amethysts', ''),
(29, 7, 7, 'Detailed, life-sized dragonborn skull cast in electrum', ''),
(29, 8, 8, 'Silver and gold brooch', ''),
(29, 9, 9, 'Obsidian statuette with gold fittings and inlay', ''),
(29, 10, 10, 'Painted gold war mask', ''),
(30, 1, 1, 'Fine gold chain set with a fire opal', ''),
(30, 2, 2, 'Old masterpiece painting', ''),
(30, 3, 3, 'Embroidered silk and velvet mantle set with numerous moonstones', ''),
(30, 4, 4, 'Platinum bracelet set with an emerald', ''),
(30, 5, 5, 'Embroidered glove set with jewel chips', ''),
(30, 6, 6, 'Jeweled anklet', ''),
(30, 7, 7, 'Gold music box', ''),
(30, 8, 8, 'Gold circlet set with four aquamarines', ''),
(30, 9, 9, 'Eye patch decorated with tiny blue sapphires and moonstones', ''),
(30, 10, 10, 'A necklace string of small pink pearls', ''),
(31, 1, 1, 'Jeweled gold crown', ''),
(31, 2, 2, 'Jeweled platinum ring', ''),
(31, 3, 3, 'Gold statuette set with rubies', ''),
(31, 4, 4, 'Gold cup set with emeralds', ''),
(31, 5, 5, 'Gold jewelry box with platinum filigree', ''),
(31, 6, 6, 'Set of gold nesting dolls', ''),
(31, 7, 7, 'Jade game board with gold playing pieces', ''),
(31, 8, 8, 'Bejeweled ivory drinking horn with gold filigree', ''),
(31, 9, 9, 'Gilded royal coach or funeral barge', ''),
(31, 10, 10, 'Ceremonial gold armor with black pearls', '')
;
